CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE IF NOT EXISTS products(
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK: product id',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name VARCHAR(255) NOT NULL,
  sku VARCHAR(16) NOT NULL,
  price DECIMAL NOT NULL,
  description TEXT
) DEFAULT CHARSET utf8 COMMENT 'This is the products table';
CREATE TABLE IF NOT EXISTS warehouses(
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'PK: warehouse id',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  location TEXT NOT NULL
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE IF NOT EXISTS warehouse_products(
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  warehouseId int NOT NULL,
  productId int NOT NULL,
  FOREIGN KEY(warehouseId) REFERENCES warehouses(id) ON DELETE CASCADE,
  FOREIGN KEY(productId) REFERENCES products(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';